f = open(r'apresentacao_15min/slides_interativos.html', encoding='utf-8').read()
print('Sections:', f.count('<section'))
print('h2:', f.count('<h2'))
print('Timer:', 'timer' in f.lower())
print('SSE:', 'SSE' in f)
print('Haversine:', 'haversine' in f.lower() or 'arcsin' in f)
print('Notas/Roteiro:', 'notes-panel' in f or 'roteiro' in f.lower() or 'speaker' in f.lower())
print('Tela Cheia/fullscreen:', 'fullscreen' in f.lower())
print('Size bytes:', len(f.encode('utf-8')))
